### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by thiyagu06** [ShiftForward/mucuchies#26]
I am getting the below error when trying t build the application.
Running "uglify:<%= buildOptions.distPath %>/application.min.js" (uglify) task
{ message: 'Unexpected token name «Object», expected punc «,»',
  filename: '..\\build\\application.js',
  line: 69960,
  col: 68,
  pos: 2197971,
  stack: 'Error\n    at new JS_Parse_Error 

 Uglifying source build/application.js failed.
Warning: Uglification failed.
Unexpected token name «Object», expected punc «,».
Line 69960 in build/application.js
 Use --force to continue.

Aborted due to warnings.

**Comment by queimadus** [comment]
Try updating your npm to the latest version.

    npm install -g npm

**Comment by thiyagu06** [comment]
I tried this..still same issue..

**Comment by ruippeixotog** [comment]
Building the project should be nothing more than what is in the README - after installing npm, grunt and the project dependencies, `grunt build` should do all the build tasks successfully.

After that error happens, can you provide us the contents of your `build/application.js` file?

**Comment by thiyagu06** [comment]
I repeated the steps again..still getting the same error. please find the contents of application.js file.I cant copy the files. So i am providing the line where am getting the error.

Ember.TEMPLATES["build_widget"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["clock_widget"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["dashboard"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["embed_widget"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["graph_widget"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["gridster"] = Ember.Handlebars.template([object Object]);

Ember.TEMPLATES["html_widget"] = Ember.Handlebars.template([object Object])

**Comment by ruippeixotog** [comment]
Hmm, it seems that your problem is related to [this issue](https://github.com/stefanpenner/ember-app-kit/issues/523). Can you try `npm cache clear` and build again?

**Comment by thiyagu06** [comment]
Hi, Thanks.. above command solves the problem.
